apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpod-operator
  namespace: devpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devpod-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devpod-operator
    spec:
      containers:
        - name: devpod-operator
          image: clvx/devpod-operator:latest
          imagePullPolicy: Always
      serviceAccountName: devpod
