apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: devpod
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devpod-operator
    app.kubernetes.io/part-of: devpod-operator
    app.kubernetes.io/managed-by: kustomize
  name: devpod
  namespace: devpod
