# permissions for end users to edit devpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devpod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devpod-operator
    app.kubernetes.io/part-of: devpod-operator
    app.kubernetes.io/managed-by: kustomize
  name: devpod-editor-role
rules:
- apiGroups:
  - devpod.bitclvx.com
  resources:
  - devpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devpod.bitclvx.com
  resources:
  - devpods/status
  verbs:
  - get
