apiVersion: devpod.bitclvx.com/v1alpha1
kind: DevPod
metadata:
  labels:
    app.kubernetes.io/name: devpod
    app.kubernetes.io/instance: devpod-sample
    app.kubernetes.io/part-of: devpod-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: devpod-operator
  name: devpod-sample
spec:
  # TODO(user): Add fields here
